"""empty message

Revision ID: 128bd32b97a4
Revises: f3f0f7d08c54
Create Date: 2020-07-22 07:41:57.560292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128bd32b97a4'
down_revision = 'f3f0f7d08c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('area', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('area', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('venue', 'num_upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'num_upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('area', 'state',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('area', 'city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
