"""empty message

Revision ID: 160e364be9ad
Revises: a4c957ab4d6a
Create Date: 2020-07-23 20:24:31.771979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160e364be9ad'
down_revision = 'a4c957ab4d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('name', sa.String(length=150), nullable=True))
    op.drop_column('album', 'album')
    op.add_column('song', sa.Column('name', sa.String(length=150), nullable=True))
    op.drop_column('song', 'song')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('song', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('song', 'name')
    op.add_column('album', sa.Column('album', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('album', 'name')
    # ### end Alembic commands ###
