"""empty message

Revision ID: 191a03a80fa2
Revises: 7aa85b9eb8b8
Create Date: 2020-07-21 01:10:50.512981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191a03a80fa2'
down_revision = '7aa85b9eb8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time')
    # ### end Alembic commands ###
