"""empty message

Revision ID: 1f7cfdeef2ab
Revises: a1fb1afd16a4
Create Date: 2020-07-23 18:51:18.953593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7cfdeef2ab'
down_revision = 'a1fb1afd16a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song', sa.String(length=150), nullable=True),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('album', 'song')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('song', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_table('song')
    # ### end Alembic commands ###
