"""empty message

Revision ID: 47fa9c6cca60
Revises: d4e4ce5fec84
Create Date: 2020-07-21 23:45:11.551663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fa9c6cca60'
down_revision = 'd4e4ce5fec84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('venue_image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'venue_image_link')
    # ### end Alembic commands ###
