"""empty message

Revision ID: 5bab534a4573
Revises: 47fa9c6cca60
Create Date: 2020-07-22 00:20:53.075772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bab534a4573'
down_revision = '47fa9c6cca60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'address')
    # ### end Alembic commands ###
