"""empty message

Revision ID: 71fb8d3fbf39
Revises: cec708d8f44c
Create Date: 2020-07-20 23:30:50.024661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71fb8d3fbf39'
down_revision = 'cec708d8f44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venue', sa.Column('time_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venue', 'time', ['time_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'time_id')
    op.drop_table('time')
    # ### end Alembic commands ###
