"""empty message

Revision ID: 7aa85b9eb8b8
Revises: 71fb8d3fbf39
Create Date: 2020-07-21 01:00:43.436810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa85b9eb8b8'
down_revision = '71fb8d3fbf39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'time', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time', type_='foreignkey')
    op.drop_column('time', 'venue_id')
    # ### end Alembic commands ###
