"""empty message

Revision ID: 885e48c7045f
Revises: a910f6c517f1
Create Date: 2020-07-21 18:55:17.598030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '885e48c7045f'
down_revision = 'a910f6c517f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time')
    op.add_column('venue', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'start_time')
    op.create_table('time',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], name='time_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='time_pkey')
    )
    # ### end Alembic commands ###
