"""empty message

Revision ID: aac6d72675e9
Revises: 11df0df98ab2
Create Date: 2020-07-22 01:58:09.780205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac6d72675e9'
down_revision = '11df0df98ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('image_link', sa.String(length=500), nullable=True))
    op.drop_column('venue', 'venue_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('venue_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venue', 'image_link')
    # ### end Alembic commands ###
