"""empty message

Revision ID: f3f0f7d08c54
Revises: c55cd7425e64
Create Date: 2020-07-22 07:14:07.708858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f0f7d08c54'
down_revision = 'c55cd7425e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('state', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'state')
    op.drop_column('artist', 'city')
    # ### end Alembic commands ###
